#!/bin/bash
### ---
### name: 'LONGWAS:GWAS:GWASDATA_PREP:MERGE_PCA (2)'
### container: 'amcalejandro/longgwas:v2'
### outputs:
### - 'EUR_*_filtered.pca.tsv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export RESOURCE_DIR="/home/oiher/longGWAS/longitudinal-GWAS-pipeline/files"
export OUTPUT_DIR="/home/oiher/longGWAS/longitudinal-GWAS-pipeline/files/longGWAS_pipeline/results"
export STORE_DIR="/home/oiher/longGWAS/longitudinal-GWAS-pipeline/files/longGWAS_pipeline/results/cache"
export ADDI_QC_PIPELINE="/usr/src/ADDI-GWAS-QC-pipeline/addi_qc_pipeline.py"
export PATH="\$PATH:/home/oiher/longGWAS/longitudinal-GWAS-pipeline/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78/.exitcode
    set +u
    (sudo -n true && sudo rm -rf "$NXF_SCRATCH" || rm -rf "$NXF_SCRATCH")&>/dev/null || true
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 2048 --memory 6144m -e "NXF_TASK_WORKDIR" -v $NXF_SCRATCH:/tmp -v /home/oiher/longGWAS/longitudinal-GWAS-pipeline:/home/oiher/longGWAS/longitudinal-GWAS-pipeline -v "$NXF_TASK_WORKDIR":"$NXF_TASK_WORKDIR" -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID amcalejandro/longgwas:v2 /bin/bash -c "eval $(nxf_container_env); /usr/bin/env python3 /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f EUR_control.pca.eigenvec
    rm -f EUR_control_filtered.tsv
    ln -s /home/oiher/longGWAS/longitudinal-GWAS-pipeline/files/longGWAS_pipeline/results/cache/GLM_CS/p3_PCA_QC/EUR_control.pca.eigenvec EUR_control.pca.eigenvec
    ln -s /home/oiher/longGWAS/longitudinal-GWAS-pipeline/files/longGWAS_pipeline/results/cache/GLM_CS/p3_COVARIATES_QC/null/EUR_control_filtered.tsv EUR_control_filtered.tsv
}

nxf_unstage_outputs() {
    true
    IFS=$'\n'
    for name in $(eval "ls -1d EUR_*_filtered.pca.tsv" | sort | uniq); do
        nxf_fs_copy "$name" /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78
    done
    unset IFS
}

nxf_unstage_controls() {
    true
    cp .command.out /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78/.command.out || true
    cp .command.err /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78/.command.err || true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH="$(set +u; nxf_mktemp $TMPDIR)"
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/oiher/longGWAS/longitudinal-GWAS-pipeline/work/e6/67bdb7e72d56d0de8866bca49eba78/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
